#pragma once

#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <sstream>
#include <algorithm>

#include "Validation.h"

/**
 * @brief <B>WordPiece</B> is a subword tokenization algorithm used by BERT to handle
 * <B>Out-Of-Vocabulary (OOV)</B> problem. Instead of assigning a unique ID to every
 * single word in input data, it breaks down into common meaningful sub-parts.
 *
 * <list type="bullet">
 * <item><B>Common words</B> are kept whole: <c>play</c>, <c>run</c></item>
 * <item><B>Complex/Rare Words</B> are broken down:
 * <c>playing</c> -> <c>play</c> + <c>##ing</c></item>
 * <item>The <c>##</c> prefix indicates that a subword that attaches to previous token.</item>
 * </list>
 *
 * @remark <c>WordPieceTokenizer</c> is implemented to integrate <c>WordPiece</c> to <c>BERT</c>
 * (Bidirectional Encoder Representations from Transformers) model. Tokenizer should run before
 * <c>BERT</c> model. Model will see IDs generated by tokenizer; tokenizer will perform converting
 * strings to IDs.
 */
class WordPieceTokenizer {
public:
    // Token string -> id.
    std::map<std::string, std::size_t> vocab;
    // Id -> token string (the inverse of vocab).
    std::vector<std::string> idToWord;
    // Ids of BERT's special tokens; set by loadVocab() when vocab file
    // lists them, otherwise left at 0.
    std::size_t unkId = 0;
    std::size_t clsId = 0;
    std::size_t sepId = 0;
    std::size_t padId = 0;
    std::size_t maskId = 0;

    WordPieceTokenizer() {}

    /**
     * @brief Loads a vocabulary file with one token per line; a token's id is
     * its line number. Also records ids of [UNK], [CLS], [SEP], [PAD] and
     * [MASK] if present. Replaces any previously loaded vocabulary.
     *
     * @param vocabPath Path to vocab file. If it cannot be opened, an
     * error is printed and tokenizer is left unchanged.
     */
    void loadVocab(const std::string& vocabPath) {
        std::ifstream file(vocabPath);
        if (!file.is_open()) {
            std::cerr << "Failed to open vocab file: " << vocabPath << std::endl;
            return;
        }
        idToWord.clear();
        vocab.clear();

        std::string line;
        std::size_t idx = 0;
        
        while (std::getline(file, line)) {
            // Trim newline
            if (!line.empty() && line.back() == '\r') {
                line.pop_back();
            }
            if (!line.empty() && line.back() == '\n') {
                line.pop_back();
            }
            vocab[line] = idx;
            idToWord.push_back(line);
            if (line == "[UNK]") {
                unkId = idx;
            }
            if (line == "[CLS]") {
                clsId = idx;
            }
            if (line == "[SEP]") {
                sepId = idx;
            }
            if (line == "[PAD]") {
                padId = idx;
            }
            if (line == "[MASK]") {
                maskId = idx;
            }
            idx++;
        }
        std::cout << "Loaded vocab size: " << vocab.size() << std::endl;
    }

    /**
     * @brief Basic splitting by whitespace: first stage of tokenization,
     * turning a sentence into whole words.
     *
     * @param text Input text (ASCII is assumed).
     * @return words in order, with whitespace removed.
     */
    std::vector<std::string> basicTokenize(const std::string& text) {
        std::vector<std::string> words;
        std::string current;
        for (char c : text) {
            if (std::isspace(c)) {
                if (!current.empty()) {
                    words.push_back(current);
                    current.clear();
                }
            }
            // Simplified: splits on whitespace only (assumes pre-cleaned
            // input), unlike BERT's basic tokenizer which also splits on
            // punctuation.
            else {
                current += c;
            }
        }

        if (false == current.empty()) {
            words.push_back(current);
        }
        return words;
    }

    /**
     * @brief Splits one word into subword pieces using greedy
     * longest-match-first against vocabulary: take longest prefix that
     * is in vocab, then repeat on remainder, marking every piece after
     * first with "##".
     *
     * @param word A single word (no whitespace).
     * @return pieces, e.g. "playing" -> {"play", "##ing"}; or {"[UNK]"} if
     * any part cannot be matched or word is longer than 100 characters.
     */
    std::vector<std::string> wordPieceTokenize(const std::string& word) {
        // Safety for too long words
        if (word.size() > 100) {
            return { "[UNK]" };
        }

        std::vector<std::string> subwords;
        std::string current = word;
        bool isBad = false;
        std::size_t start = 0;

        while (start < word.length()) {
            std::size_t end = word.length();
            std::string curSubstr;
            bool found = false;
            // Greedy Longest-Match-First
            while (start < end) {
                std::string substr = word.substr(start, end - start);
                if (start > 0) {
                    // Add continuation prefix
                    substr = "##" + substr; 
                }
                if (vocab.count(substr)) {
                    curSubstr = substr;
                    found = true;
                    break;
                }
                end--;
            }

            if (false == found) {
                isBad = true;
                break;
            }
            subwords.push_back(curSubstr);
            start = end;
        }

        if (isBad) {
            return { "[UNK]" };
        }

        return subwords;
    }

    /**
     * @brief Converts text to token ids: split into words, split each word
     * into subword pieces, then map every piece to its id (unkId if missing).
     *
     * @param text Input text; casing must match vocabulary.
     * @return Token ids, without special tokens.
     * @throws InvalidSizeError If no vocabulary has been loaded.
     */
    std::vector<std::size_t> encode(const std::string& text) {
        // Without a vocabulary every piece would silently become [UNK] (id 0).
        validation::requireNonEmpty(vocab.size(), "WordPiece vocabulary (call loadVocab() first)");

        std::vector<std::string> words = basicTokenize(text);
        std::vector<std::size_t> ids;
        for (const auto& w : words) {
            // Lowercase logic should go here if using uncased model
            // For now assume input matches vocab casing
            std::vector<std::string> sub = wordPieceTokenize(w);
            for (const auto& s : sub) {
                if (vocab.count(s)) {
                    ids.push_back(vocab[s]);
                }
                else {
                    ids.push_back(unkId);
                }
            }
        }
        return ids;
    }

    /**
     * @brief Encodes a one- or two-sentence input in BERT's layout:
     * [CLS] A [SEP] and, if textB is given, B [SEP].
     *
     * @param textA First sentence.
     * @param textB Optional second sentence.
     * @return Token ids including special tokens.
     */
    std::vector<std::size_t> encodeSequence(
        const std::string& textA, 
        const std::string& textB = "") {

        std::vector<std::size_t> ids;
        ids.push_back(clsId);

        std::vector<std::size_t> partA = encode(textA);
        ids.insert(ids.end(), partA.begin(), partA.end());
        ids.push_back(sepId);

        if (false == textB.empty()) {
            std::vector<std::size_t> partB = encode(textB);
            ids.insert(ids.end(), partB.begin(), partB.end());
            ids.push_back(sepId);
        }

        return ids;
    }
};